sparkdoor/apps/common/urls.py
"""
urls.py - `common` app url routes module.
"""
from django.conf.urls import patterns, include, url

from . import views


urlpatterns = patterns('',
    url(r'^api/id-card-open$',
        views.IDCardOpenView.as_view(),
        name='id-card-open'
    ),

    url(r'^profile$',
        views.ProfileView.as_view(),
        name='profile'
    ),

    url(r'^$',
        views.HomeView.as_view(),
        name='home'
    )
)

sparkdoor/apps/spark/urls.py
"""
urls.py - `spark` app url routes module.
"""
from django.conf.urls import patterns, include, url

from . import views


urlpatterns = patterns('',

    url(r'^devices/$',
        views.DeviceAPIView.as_view(),
        name='devices-list'
    ),
    
    url(r'^devices/(?P<pk>\d+)/$',
        views.DeviceAPIView.as_view(),
        name='devices-detail'
    ),

    url(r'^devices/(?P<pk>\d+)/(?P<action>[\w\d-]+)/$',
        views.DeviceAPIView.as_view(),
        name='devices-action'
    )
)

sparkdoor/urls.py
"""
urls.py - top-level url routes module.
"""
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^',
        include('sparkdoor.apps.common.urls', namespace='common')
    ),

    url(r'^api/',
        include('sparkdoor.apps.spark.urls')
    ),

    url(r'^admin/',
        include(admin.site.urls)
    ),

    url(r'^accounts/',
        include('allauth.urls')
    )
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug_toolbar__/',
            include(debug_toolbar.urls)
        )
    )

sparkdoor/apps/common/models.py
"""
models.py - `common` app models module.
"""
import os
import binascii
from datetime import datetime

from django.db import models

from sparkdoor.apps.spark.models import Device


class DoorEvent(models.Model):
    """
    Timeseries data for events that are recorded by the door app.
    """
    OPEN_EVENT = 'open',
    USE_PASS_EVENT = 'use_pass'
    EVENTS = (
        (OPEN_EVENT, 'open'),
        (USE_PASS_EVENT, 'use pass')
    )

    device = models.ForeignKey(Device)
    time = models.DateTimeField(auto_now=True)
    event = models.CharField(max_length=50, blank=False, choices=EVENTS)
    event_data = models.TextField(blank=True)


class DoorPass(models.Model):
    """
    Acts as a shareable invite with expiration and/or finite-use rules
    for allowing an anonymous user to operate a door app device.
    """
    token = models.CharField(max_length=40, primary_key=True)
    device = models.ForeignKey(Device)
    expires_at = models.DateTimeField(null=True)
    use_limit = models.IntegerField(null=True)
    uses = models.IntegerField(default=0)

    def is_expired(self):
        """
        Test if this token is expired or not.
        """
        expired_date_reached = False
        use_limit_reached = False
        if self.expires_at:
            expired_date_reached = self.expires_at < datetime.now()
        if self.use_limit:
            use_limit_reached = self.uses >= self.use_limit
        return expired_date_reached or use_limit_reached

    def save(self, *args, **kwargs):
        """
        Add the token if not present.
        """
        if not self.token:
            self.token = self.generate_token()
        return super(self.__class__, self).save(*args, **kwargs)

    def generate_token(self):
        """
        Generate a random 20 character hex token.
        """
        return binascii.hexlify(os.urandom(20)).decode()


class IDCard(models.Model):
    """
    Stores RFID cards that can be registered with a door and used to
    open it.
    """
    uid = models.CharField(max_length=10, blank=False)
    device = models.ForeignKey(Device)

sparkdoor/apps/spark/models.py
"""
models.py - `spark` app models module.
"""
from datetime import timedelta

from django.db import models
from django.conf import settings
from django.utils import timezone

from .services import SparkCloud, CloudDevice, ServiceError
from .settings import SparkSettings


class CloudCredentialsManager(models.Manager):
    """
    Custom model manager for `CloudCredentials`.
    """
    def cloud_service(self):
        """
        Get a cloud service instance initialized with the most current
        credentials.
        """
        latest = self._latest()
        if latest is None:
            return None
        return SparkCloud(SparkSettings().API_URI, latest.access_token)

    def _access_token(self):
        """
        Get the most recent valid `access_token`, if one isn't found
        then None is returned.
        """
        latest = self._latest()
        if latest is None:
            return None
        return latest.access_token

    def refresh_token(self):
        """
        Check if the access token will expire soon, if so then attempt
        to find any existing tokens on the cloud account. If no existing
        tokens are found then a new one will be requested.
        """
        latest = self._latest()
        if latest is None or latest.expires_soon():
            cloud = SparkCloud(SparkSettings().API_URI)
            self._discover_tokens(cloud)
            if self._access_token() is None:
                self._renew_token(cloud)

    def _renew_token(self, cloud):
        """
        Get a new token from the cloud service and record it.
        """
        s = SparkSettings()
        token, expires_at = cloud.renew_token(s.USERNAME, s.PASSWORD)
        CloudCredentials(access_token=token, expires_at=expires_at).save()

    def _discover_tokens(self, cloud):
        """
        Get existing tokens from the cloud service and save the most
        recent.
        """
        s = SparkSettings()
        token, expires_at = cloud.discover_tokens(s.USERNAME, s.PASSWORD)
        if (token is not None and expires_at is not None and
                not self.filter(access_token=token).exists()):
            CloudCredentials(access_token=token, expires_at=expires_at).save()

    def _latest(self):
        """
        Get the latest valid credentials or return None.
        """
        try:
            return self.get_queryset().filter(
                    expires_at__gt=timezone.now()
                ).latest(
                    'expires_at'
                )
        except CloudCredentials.DoesNotExist:
            return None


class CloudCredentials(models.Model):
    """
    Stores credentials to access a Spark cloud service.
    """
    access_token = models.CharField(max_length=250, blank=False, unique=True)
    expires_at = models.DateTimeField()

    def expires_soon(self):
        """
        Determine if these credentials are still within the exipiration
        date.
        """
        window = SparkSettings().RENEW_TOKEN_WINDOW
        return self.expires_at <= (timezone.now() + timedelta(seconds=window))

    objects = CloudCredentialsManager()


class DeviceManager(models.Manager):
    """
    Custom query set for `Device` model.
    """
    def for_user(self, user):
        """
        Get a list of devices for a user.
        """
        return self.filter(user=user)

    def by_name(self, user, name):
        """
        Get a device for a given device name.
        """
        return self.for_user(user).get(name=name)

    def by_device_id(self, user, id):
        """
        Get a device by an id.
        """
        return self.for_user(user).get(device_id=id)


class Device(models.Model):
    """
    Stores information about a Spark device.
    """
    device_id = models.CharField(max_length=250, blank=False, unique=True)
    name = models.CharField(max_length=250, blank=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False)
    app_name = models.CharField(max_length=100, blank=False, default='default')

    objects = DeviceManager()

    class Meta:
        unique_together = ('name', 'user')

    def call(self, func_name, func_args):
        """
        Call a function on this device and return the result which will
        always be an integer for a successfull call.
        """
        return self._cloud_device.call(func_name, func_args)
    call.do_not_call_in_templates = True

    def read(self, var_name):
        """
        Read the value of a variable.
        """
        return self._cloud_device.read(var_name)

    def get_app(self):
        """
        Use the `APPS` entry in the `SPARK` settings to get a
        `spark.views.DeviceAppBase` subclass for this device.
        """
        app_class = SparkSettings().APPS.get(self.app_name, SparkSettings().DEFAULT_APP)
        return app_class(self)

    @property
    def variables(self):
        """
        The available variables for this device as a dictionary mapping
        a name to a type (either 'int32', 'string', or 'double').
        """
        return self._cloud_device.variables

    @property
    def functions(self):
        """
        The available functions for this device in a list.
        """
        return self._cloud_device.functions

    @property
    def _cloud_device(self):
        """
        Get a `CloudDevice` instance from the Spark cloud and cache it.
        """
        if not hasattr(self, '_cached_cloud_device'):
            cloud = CloudCredentials.objects.cloud_service()
            self._cached_cloud_device = cloud.device(self.device_id)
        if self._cached_cloud_device is None:
            raise ServiceError(502)
        return self._cached_cloud_device

sparkdoor/apps/common/forms.py
"""
forms.py - form classes for the `common` app.
"""
from django.forms import ModelForm

from sparkdoor.apps.spark.models import CloudCredentials, Device


class RegisterDeviceForm(ModelForm):
    """
    From for registering new spark devices. This form ensures that the
    `device_id` isn't already claimed and exists in the Spark cloud.
    """
    class Meta:
        model = Device
        fields = ['user', 'device_id', 'name']

    def clean(self):
        """
        Validate that the `device_id` is correct by first looking for
        Devices with this id in the database and then by attempting to
        read the `app_name` variable.

        If the form isn't valid, then there's no point in running these
        checks so just return.
        """
        data = super(RegisterDeviceForm, self).clean()
        device_id = data['device_id']
        # Don't bother checking with the cloud if this device id is
        # already stored.
        if not Device.objects.filter(device_id=device_id).exists():
            device = CloudCredentials.objects.cloud_service().device(device_id)
            if device is None:
                self.add_error('device_id', 'This device id is invalid.')
        return data

sparkdoor/apps/common/views.py
"""
views.py - `common` app views module.
"""
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import TemplateView

from rest_framework import views, response, serializers, permissions

from sparkdoor.apps.spark.views import UserDevicesViewBase

from .models import IDCard


class HomeView(TemplateView):
    """
    The home page view.
    """
    template_name = 'common/home.html'


class ProfileView(UserDevicesViewBase):
    """
    The user profile view, which provides a list of the user's devices
    and a device registration form.
    """
    template_name = 'common/devices.html'
    success_url = reverse_lazy('common:profile')


class IDCardOpenSerializer(serializers.Serializer):
    """
    Serializer for the `IDCardOpenView`.
    """
    device_id = serializers.CharField(max_length=250)
    card_uid = serializers.CharField(max_length=200)


class IDCardOpenView(views.APIView):
    """
    API view that is POSTed to by a door device. The POST data must
    include a `device_id` and a `card_uid`. If a match is successfull,
    indicating that the door can be opened, a 200 is returned, otherwise
    a 403. 
    """
    permission_classes = (permissions.AllowAny,)

    def post(self, request, *args, **kwargs):
        """
        POST handler.
        """
        serializer = IDCardOpenSerializer(data=request.DATA)
        if not serializer.is_valid():
            print(serializer.errors)
            return response.Response('Invalid request data.', 400)
        if self.can_open_door(serializer.data):
            return response.Response('Valid ID card.', 200)
        return response.Response('Invalid ID card.', 403)

    def can_open_door(self, data):
        """
        Check if the provided `card_uid` is allowed to open the door
        that corresponds to the provided `device_id`.
        """
        try:
            cards = IDCard.objects.filter(device__device_id=data['device_id'],
                uid=data['card_uid'])
        except:
            return False
        return cards.count() > 0

sparkdoor/apps/common/templates/common/base.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html>
<head>
  {% block meta %}{% endblock meta %}

  <title>SparkDoor {% block title %}{% endblock title %}</title>

  <link rel="stylesheet" media="screen" href="{% static 'css/bootstrap.min.css' %}" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  {% block base_css %}
    <link rel="stylesheet" media="screen" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-modal/2.2.5/css/bootstrap-modal-bs3patch.css" />-->
  {% endblock base_css %}

  {# Custom CSS #}
  {% block css %}{% endblock css %}

  {# Base head JS #}
  {% block base_js %}
  {# This will need to be updated to a custom build when we go to production #}
    <script src="http://modernizr.com/downloads/modernizr-latest.js"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
  {% endblock base_js %}

  {# Custom head JS #}
  {% block head_js %}{% endblock head_js %}
</head>

<body {% block body_attr %}{% endblock body_attr %}>

  {% block header %}
  <div id="wrap">
    <header>
      <nav class="navbar navbar-static-top navbar-default" role="navigation">
        <div class="container-fluid">
          <!-- Groups all the good stuff for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "common:home"%}">SparkDoor</a>
          </div>

          <div class="collapse navbar-collapse" id="nav-collapse">
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li class="login"><a href="{% url 'account_logout' %}">Logout</a></li>
              {% else %}
                <li class="login"><a href="{% url 'account_login' %}">Login</a></li>
                <li class="login"><a href="{% url 'account_signup' %}">Signup</a></li>
              {% endif %}
            </ul>
          </div>

        </div>
      </nav>
      {% block innerheader %}
      {% endblock innerheader %}
    </header>
  </div>
  <!-- End Navigation -->
  <div class="container">
  {% endblock header %}
      {% block messages %}
      {% for msg in messages %}
      {# Display django.contrib.messages as Bootstrap alerts #}
      {% bootstrap_messages %}
      {% endfor %}
      {% endblock messages %}

      {% block base_content %}
      {% block content %}{% endblock content %}
      {% endblock base_content %}
    <!-- End Content -->
  </div>
  <!-- Footer -->
  {% block footer %}{% endblock footer %}
  <!-- End Footer -->

  {% block base_body_js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-modal/2.2.5/js/bootstrap-modal.min.js"></script>-->
  {% endblock base_body_js %}
  {# Custom JS #}
  {% block body_js %}{% endblock body_js %}
</body>
</html>

sparkdoor/apps/common/templates/common/devices.html
{% extends 'common/base.html' %}

{% load bootstrap3 %}
{% load static %}

{% block title %}Devices{% endblock title %}

{% block body_js %}
<script src="{% static 'js/qrcode.min.js' %}"></script>
<script src="{% static 'js/door_app.js' %}"></script>
{% endblock body_js %}

{% block content %}
<script>
function csrfSafeMethod(method) {
  // these HTTP methods do not require CSRF protection
  return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
function getCookie(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie != '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
      var cookie = jQuery.trim(cookies[i]);
      // Does this cookie string begin with the name we want?
      if (cookie.substring(0, name.length + 1) == (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}
$(document).ready(function(evt) {
  var csrftoken = getCookie('csrftoken');
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });
  $('#qr-btn').on('click', function() {
    $("#reader").show();
  });
  $('#device_id').on('focus', function() {
    $("#reader").hide();
  });
  $('#reader').html5_qrcode(function(data) {
    $('#device_id').val(data);
    $("#reader").hide();
  }, function () {
  }, function () {
  });
  $('#door_unlock_modal').on('show.bs.modal', function(evt) {
    var modal = $(this);
    var uri = $(evt.relatedTarget).data('uri');
    var loader = modal.find('.ajax-loader');
    var footer = modal.find('.modal-footer');
    var text = modal.find('.modal-text');
    modal.find('.door-name').text($(evt.relatedTarget).parents('.door-app').find('.device-name').text());
    loader.show();
    footer.hide();
    text.hide();
    $.post(uri).always(function() {
      loader.hide();
      footer.show();
    }).done(function(data, status, jqXHR) {
      text.show().text('Opened!');
    }).fail(function(data, status, jqXHR) {
      text.show().text('Door does not appear to be connected.');
    });
  });
  $('#pair_card_modal').on('show.bs.modal', function(evt) {
    var modal = $(this);
    var uri = $(evt.relatedTarget).data('uri');
    var loader = modal.find('.ajax-loader');
    var footer = modal.find('.modal-footer');
    var text = modal.find('.modal-text');
    loader.show();
    footer.hide();
    text.text('Place ID card against card reader to pair it with this door.');
    $.post(uri).always(function() {
      loader.hide();
      footer.show();
    }).done(function(data, status, jqXHR) {
      text.text('ID card successfully paired!');
    }).fail(function(data, status, jqXHR) {
      text.text('Door is either not connected or the ID card could not be read.');
    });
  });
});
</script>
<div class="modal fade" id="door_unlock_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Opening <span class="door-name"></span></h4>
      </div>
      <div class="modal-body">
        <img class="center-block ajax-loader" src="{% static 'img/ajax-loader.gif' %}">
        <p class="modal-text"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Okay</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="pair_card_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Pairing New ID Card</h4>
      </div>
      <div class="modal-body">
        <img class="center-block ajax-loader" src="{% static 'img/ajax-loader.gif' %}">
        <p class="modal-text"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Okay</button>
      </div>
    </div>
  </div>
</div>
<h1>Your Devices</h1>
<div class="row">
  {% for device in devices %}
  <div class="col-lg-4 col-md-6 col-sm-12">{{ device }}</div>
  {% empty %}
  <div class="col-lg-12">
    <div class="panel panel-default door-app">
      <div class="panel-heading">
        <h4><small class="text-primary">{% bootstrap_icon "hdd" %}</small> None yet :(</h4>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><small class="text-primary">{% bootstrap_icon "plus" %}</small> Register New Device</h4>
  </div>
  <div class="panel-body">
    <form role="form" class="form-horizontal" method="POST">
      {% csrf_token %}
      <div class="form-group {% if form.name.errors %}has-error{% endif %}">
        <label for="id_name" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="id_name" name="name" placeholder="Give your device a name!">
          {{ form.name.errors|first }}
        </div>
      </div>
      <div class="form-group {% if form.device_id.errors %}has-error{% endif %}">
        <label for="id_device_id" class="col-sm-2 control-label">ID</label>
        <div class="col-sm-10">
          <div class="input-group">
            <input id="device_id" type="text" class="form-control" id="id_device_id" name="device_id" placeholder="Enter your device ID">
            {{ form.device_id.errors|first }}
            <span class="input-group-btn">
              <button class="btn btn-default" type="button" id="qr-btn">Read QR</button>
            </span>
          </div>
        </div>
      </div>
      <div id="reader" style="width:300px;height:250px;display:none"></div>
      <div class="form-group" id="submit-div">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Register</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

sparkdoor/apps/common/templates/common/door_app.html
{% load bootstrap3 %}

<div class="panel panel-default door-app">
  <div class="panel-heading">
    <h4><small class="text-primary">{% bootstrap_icon "hdd" %}</small>&nbsp;<span class="device-name">{{ device.name }}</span></h4>
  </div>
  <ul class="list-group">
    <li class="list-group-item">Last opened on 10/12/2014</li>
    <li class="list-group-item">Some other info</li>
  </ul>
  <div class="panel-footer">
    <div class="btn-group btn-group-justified">
      <a class="btn btn-primary" data-toggle="modal" data-target="#door_unlock_modal" data-uri="{% url 'devices-action' pk=device.id action='open' %}">Unlock</a>
      <a class="btn btn-default" data-toggle="modal" data-target="#pair_card_modal" data-uri="{% url 'devices-action' pk=device.id action='pair_id_card' %}">Pair ID Card</a>
    </div>
  </div>
</div>

sparkdoor/apps/common/templates/common/home.html
{% extends 'common/base.html' %}

{% block innerheader %}
<div class="container">
  <h1 id="header" class="text-center">SparkDoor</h1>
  <h2 class="text-center">Its like your door, but smarter</h2>
  <div class="center-block text-center">
    {% if user.is_authenticated %}
    <a href="{% url 'common:profile' %}" class="btn btn-btn-lg btn-default btn-splash">My Devices</a>
    {% else %}
    <a href="{% url 'account_signup' %}" class="btn btn-btn-lg btn-default btn-splash">Sign up now</a>
    {% endif %}
  </div>
</div>
{% endblock innerheader %}

{% block content %}
<div class="extend"></div>
{% endblock content %}